services:
  postgres:
    image: postgres:17-alpine
    container_name: postgres
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '${DB_PORT}:5431'
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER"]  
      timeout: 10s
      interval: 1s
      retries: 10

  migrate:
    image: k0nnte/prisma-migrate:v1
    container_name: migrate
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    restart: 'on-failure'
    networks:
      - app-network


    
          
    

networks:
    app-network:
      driver: bridge


volumes:
  postgres_data:

